pipeline {
    agent any
    tools {
    //adding the tools
        maven "Maven 3.6.0"
        jdk "jdk8"
        
    }

    stages {
        stage('compile stage') {
            
            steps {
                sh 'mvn clean '
                  
             }

        }

                       
        stage('test stage') {

            steps {
                             
                sh 'mvn test'
                                               

            }


        }
        stage('install stage') {
                            
             steps {
                  sh 'mvn install'
                                                  

              }

        }
         


 

    }

}
